services:

  langkah-api:
    container_name: langkah-api
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - langkah-api/.env
    restart: on-failure
    volumes:
      - ./langkah-api:/app
