"""Updated User model to allow nullable fields

Revision ID: ef80c8ababad
Revises: ca1296c1d73a
Create Date: 2024-11-15 14:13:43.957714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef80c8ababad'
down_revision: Union[str, None] = 'ca1296c1d73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'body_metrics', ['id'])
    op.create_unique_constraint(None, 'food_products', ['id'])
    op.create_unique_constraint(None, 'meals', ['id'])
    op.alter_column('users', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='sex'),
               nullable=True)
    op.alter_column('users', 'activity_level',
               existing_type=postgresql.ENUM('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', name='activitylevel'),
               nullable=True)
    op.alter_column('users', 'goal',
               existing_type=postgresql.ENUM('WEIGHT_LOSS', 'MUSCLE_GAIN', 'MAINTAIN', 'BODY_RECOMPOSITION', name='goal'),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'goal',
               existing_type=postgresql.ENUM('WEIGHT_LOSS', 'MUSCLE_GAIN', 'MAINTAIN', 'BODY_RECOMPOSITION', name='goal'),
               nullable=False)
    op.alter_column('users', 'activity_level',
               existing_type=postgresql.ENUM('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', name='activitylevel'),
               nullable=False)
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='sex'),
               nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'meals', type_='unique')
    op.drop_constraint(None, 'food_products', type_='unique')
    op.drop_constraint(None, 'body_metrics', type_='unique')
    # ### end Alembic commands ###
